export const navLinks = [
  {
    href: "#",
    label: "Video",
    dropdownItems: [
      {
        title: "Categories",
        items: [
          { label: "Intros", href: "#" },
          { label: "Animations", href: "#" },
          { label: "Music Visualizations", href: "#" },
          { label: "Video Editing", href: "#" },
          { label: "YouTube Videos", href: "#" },
          { label: "Slideshows", href: "#" },
          { label: "Video Presentations", href: "#" },
          { label: "Video Invitations", href: "#" },
          { label: "Opener Animations", href: "#" },
          { label: "Greeting Cards", href: "#" },
        ],
      },
      {
        title: "Featured",
        items: [
          { label: "Animated Explainers", href: "#" },
          { label: "Youtube Intros", href: "#" },
          { label: "Outro Animation", href: "#" },
          { label: "2D Animations", href: "#" },
          { label: "Animated Texts", href: "#" },
          { label: "Logo Animations", href: "#" },
          { label: "Birthday Greetings", href: "#" },
          { label: "Animated e-cards", href: "#" },
          { label: "World of Videos", href: "#" },
          { label: "Greeting Cards", href: "#" },
        ],
      },
    ],
  },
  {
    href: "#",
    label: "Website",
    dropdownItems: [
      {
        title: "Categories",
        items: [
          { label: "Intros1", href: "#" },
          { label: "Animations", href: "#" },
          { label: "Music Visualizations", href: "#" },
          { label: "Video Editing", href: "#" },
          { label: "YouTube Videos", href: "#" },
          { label: "Slideshows", href: "#" },
          { label: "Video Presentations", href: "#" },
          { label: "Video Invitations", href: "#" },
          { label: "Opener Animations", href: "#" },
          { label: "Greeting Cards", href: "#" },
        ],
      },
      {
        title: "Featured",
        items: [
          { label: "Animated Explainers1", href: "#" },
          { label: "Youtube Intros", href: "#" },
          { label: "Outro Animation", href: "#" },
          { label: "2D Animations", href: "#" },
          { label: "Animated Texts", href: "#" },
          { label: "Logo Animations", href: "#" },
          { label: "Birthday Greetings", href: "#" },
          { label: "Animated e-cards", href: "#" },
          { label: "World of Videos", href: "#" },
          { label: "Greeting Cards", href: "#" },
        ],
      },
    ],
  },
  {
    href: "#",
    label: "Logos",
    dropdownItems: [
      {
        title: "Categories",
        items: [
          { label: "Intros2", href: "#" },
          { label: "Animations", href: "#" },
          { label: "Music Visualizations", href: "#" },
          { label: "Video Editing", href: "#" },
          { label: "YouTube Videos", href: "#" },
          { label: "Slideshows", href: "#" },
          { label: "Video Presentations", href: "#" },
          { label: "Video Invitations", href: "#" },
          { label: "Opener Animations", href: "#" },
          { label: "Greeting Cards", href: "#" },
        ],
      },
      {
        title: "Featured",
        items: [
          { label: "Animated Explainers", href: "#" },
          { label: "Youtube Intros", href: "#" },
          { label: "Outro Animation", href: "#" },
          { label: "2D Animations", href: "#" },
          { label: "Animated Texts", href: "#" },
          { label: "Logo Animations", href: "#" },
          { label: "Birthday Greetings", href: "#" },
          { label: "Animated e-cards", href: "#" },
          { label: "World of Videos", href: "#" },
          { label: "Greeting Cards", href: "#" },
        ],
      },
    ],
  },
  {
    href: "#",
    label: "Mockups",
    dropdownItems: [
      {
        title: "Categories",
        items: [
          { label: "Intros", href: "#" },
          { label: "Animations", href: "#" },
          { label: "Music Visualizations", href: "#" },
          { label: "Video Editing", href: "#" },
          { label: "YouTube Videos", href: "#" },
          { label: "Slideshows", href: "#" },
          { label: "Video Presentations", href: "#" },
          { label: "Video Invitations", href: "#" },
          { label: "Opener Animations", href: "#" },
          { label: "Greeting Cards", href: "#" },
        ],
      },
      {
        title: "Featured",
        items: [
          { label: "Animated Explainers", href: "#" },
          { label: "Youtube Intros", href: "#" },
          { label: "Outro Animation", href: "#" },
          { label: "2D Animations", href: "#" },
          { label: "Animated Texts", href: "#" },
          { label: "Logo Animations", href: "#" },
          { label: "Birthday Greetings", href: "#" },
          { label: "Animated e-cards", href: "#" },
          { label: "World of Videos", href: "#" },
          { label: "Greeting Cards", href: "#" },
        ],
      },
    ],
  },
  {
    href: "#",
    label: "Graphics",
    dropdownItems: [
      {
        title: "Categories",
        items: [
          { label: "Intros", href: "#" },
          { label: "Animations", href: "#" },
          { label: "Music Visualizations", href: "#" },
          { label: "Video Editing", href: "#" },
          { label: "YouTube Videos", href: "#" },
          { label: "Slideshows", href: "#" },
          { label: "Video Presentations", href: "#" },
          { label: "Video Invitations", href: "#" },
          { label: "Opener Animations", href: "#" },
          { label: "Greeting Cards", href: "#" },
        ],
      },
      {
        title: "Featured",
        items: [
          { label: "Animated Explainers", href: "#" },
          { label: "Youtube Intros", href: "#" },
          { label: "Outro Animation", href: "#" },
          { label: "2D Animations", href: "#" },
          { label: "Animated Texts", href: "#" },
          { label: "Logo Animations", href: "#" },
          { label: "Birthday Greetings", href: "#" },
          { label: "Animated e-cards", href: "#" },
          { label: "World of Videos", href: "#" },
          { label: "Greeting Cards", href: "#" },
        ],
      },
    ],
  },
  {
    href: "#",
    label: "Explore AI",
    dropdownItems: [
      {
        title: "Categories",
        items: [
          { label: "Intros", href: "#" },
          { label: "Animations", href: "#" },
          { label: "Music Visualizations", href: "#" },
          { label: "Video Editing", href: "#" },
          { label: "YouTube Videos", href: "#" },
          { label: "Slideshows", href: "#" },
          { label: "Video Presentations", href: "#" },
          { label: "Video Invitations", href: "#" },
          { label: "Opener Animations", href: "#" },
          { label: "Greeting Cards", href: "#" },
        ],
      },
      {
        title: "Featured",
        items: [
          { label: "Animated Explainers", href: "#" },
          { label: "Youtube Intros", href: "#" },
          { label: "Outro Animation", href: "#" },
          { label: "2D Animations", href: "#" },
          { label: "Animated Texts", href: "#" },
          { label: "Logo Animations", href: "#" },
          { label: "Birthday Greetings", href: "#" },
          { label: "Animated e-cards", href: "#" },
          { label: "World of Videos", href: "#" },
          { label: "Greeting Cards", href: "#" },
        ],
      },
    ],
  },
];
